"""fixed descripton column

Revision ID: c8280d9ed2b4
Revises: 86fa68c54a77
Create Date: 2025-11-07 21:40:00.990956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8280d9ed2b4'
down_revision = '86fa68c54a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=500),
               nullable=True)
        batch_op.drop_column('description')

    # ### end Alembic commands ###
